version: '3.9'

services:
  bot:
    image: fluxnat/tempvoice:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data # This is CRITICAL for your SQLite database
    healthcheck:
      test: [ "CMD", "node", "--eval", "process.exit(0)" ]
      interval: 30s
      timeout: 10s
      retries: 3
